name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_maps_flutter: ^2.9.0
  file_picker: ^8.0.0
  video_player: ^2.8.2
  image_picker: ^1.2.1
  shared_preferences: ^2.0.17
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  audioplayers: ^6.5.1
  record: ^6.1.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  image: images/logo.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
